version: '3.1'
services:
  db:
    #build: ./database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
  my_app:
    build:
      context: .
    environment:
      ENVIRONMENT: development
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    links:
      - db:db